parameters:
- name: envName
  type: string

- name: envDisplayName
  type: string

stages:
- stage: DeployTo${{ parameters.envDisplayName }}
  displayName: Deploy to ${{ parameters.envDisplayName }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployJob
    displayName: Deploy to ${{ parameters.envDisplayName }}
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: KubernetesManifest@0
              displayName: Apply Manifest
              inputs:
                kubernetesServiceConnection: AWS EKS Cluster
                namespace: musicfeed
                manifests: "$(Pipeline.Workspace)/k8s-manifest/updates-service.yaml"
