# kubectl create -f "updates-service.yaml"
# kubectl port-forward service/updates-service 8102:80
# kubectl port-forward service/updates-service 8103:81
# http://localhost:8102/health/ready
# kubectl delete -f "updates-service.yaml"

apiVersion: v1
kind: Service
metadata:
  name: updates-service
  labels:
    app: updates-service
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 81
    protocol: TCP
    name: grpc
  selector:
    app: updates-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: updates-service
  labels:
    app: updates-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: updates-service
  template:
    metadata:
      labels:
        app: updates-service
    spec:
      containers:
        - name: updates-service
          image: codefuller/musicfeed-updates-service:latest
          ports:
            - containerPort: 80
            - containerPort: 81
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
