name: $(Build.BuildId)

trigger: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

stages:
- template: deploy-template.yaml
  parameters:
    envName: test
    envDisplayName: Test

- template: deploy-template.yaml
  parameters:
    envName: prod
    envDisplayName: Production
