parameters:
- name: envName
  type: string

- name: envDisplayName
  type: string

stages:
- stage: DeployTo${{ parameters.envDisplayName }}
  displayName: Deploy to ${{ parameters.envDisplayName }} Environment
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployJob
    displayName: Deploy to ${{ parameters.envDisplayName }} Environment
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Artifacts
            inputs:
              # Downloading artifacts from last successfull CI build.
              buildType: specific
              project: $(System.TeamProjectId)
              # Id of "Updates Service - CI" pipeline.
              definition: 20

          - task: KubernetesManifest@0
            displayName: Apply Manifest
            inputs:
              kubernetesServiceConnection: AWS EKS Cluster
              namespace: musicfeed-${{ parameters.envName }}
              manifests: "$(Pipeline.Workspace)/K8s-manifest/updates-service.yaml"
